services:
  - type: web
    name: qr-assist-app
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run migrate && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_CLIENT
        value: pg
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: QR_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: LATE_AFTER
        value: 09:05
